# project title
# student course enrollment management system 

create database sqlproject;
use sqlproject;
create table students(studentId int primary key,
StudentName varchar(20),
Gender varchar(20),
Age int,
City varchar(20),
Email varchar(20),
Phone varchar(20),
joiningdate date);

select * from students;

create table  instructors( InstructorId int primary key,
InstructorName varchar(20),
Department varchar(20),
Experience int);
select * from instructors;

create table courses( CourseId int primary key,
courseName varchar(20),
DurationMonth int,
Fee decimal(10,2),
InstructorId int,
foreign key(InstructorId)
references instructors(InstructorId));
select * from courses;

create table Enrollments(EnrollmentId int primary key,
StudentId int,
CourseId int,
EnrollmentDate date,
CompletionStatus varchar(20),
Marks int,
foreign key (studentId)
references students(studentId),
Foreign key (CourseId)
references  courses(CourseId));
select * from enrollments;

# Business analyzing Questions

# 1.Total no of students
select count(*) as total_students
from students;
#insight
# There are total 100 students in the institute

# 2.Total no of courses
select count(*) as total_courses
from courses;
# There are total 5 courses in the institute

# 3.Total no of instructors
select count(*) as total_instructors
from instructors;
# There are total 5 instructors  in the institute

 # 4. courses with fee greater then 5000
 select * from courses
 where fee>5000;
 # for python, powerbi and data analytics courses fee is more then 5000
 
 # 5.student enrolled in courses
 select 
c.coursename,
 count(e.studentId) as total_student
 from courses c 
 join enrollments e 
 on c.courseId = e.courseId
 group by c.coursename;
 # Most of the students enrolled for the Data analytics
 
 # 6. list students with their courses
 select s.studentname,
 c.coursename
 from students s 
 join enrollments e
 on s.studentId = e.studentId
 join courses c
 on e.courseId = c.courseid;
 # maximum numbers of students are from SQL course


# 7.student who completed their course
select s.studentname,
c.coursename,
e.completionstatus
from students s
join enrollments e
on s.studentid = e.studentid
join courses c
on c.courseid = e.courseid
where completionstatus= "completed";

# 8.student who are still studing
select s.studentname,
c.coursename,
e.completionstatus
from students s
join enrollments e
on s.studentid = e.studentid
join courses c
on c.courseid = e.courseid
where completionstatus= "ongoing";


# 9.city wise student count 
select city,count(*) as total_students
from students
group by city;
# using sql query i have analyzed that most of the students are from hyderabad


# 10.Revenue generated by each course
select c.coursename,
count(e.studentid) * c.fee as revenue 
from enrollments e
join courses c 
on e.courseid = c.courseid
group by c.coursename,c.fee;
# more revenue is generated by data analytics course and less revenue generated by excel course
